# Generated by Django 6.0.6 on 2026-07-08 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pooja_service', '0003_alter_poojaservice_options_poojaservice_badge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoojaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('pooja_date', models.DateField()),
                ('pooja_time', models.TimeField()),
                ('gotra', models.CharField(blank=True, max_length=100, null=True)),
                ('sankalp_name', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('pooja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pooja_service.poojaservice')),
            ],
        ),
    ]
