# Generated by Django 6.0.6 on 2026-08-22 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_form', '0001_initial'),
        ('pooja_service', '0003_alter_poojaservice_options_poojaservice_badge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poojabooking',
            name='gotra',
        ),
        migrations.RemoveField(
            model_name='poojabooking',
            name='message',
        ),
        migrations.RemoveField(
            model_name='poojabooking',
            name='sankalp_name',
        ),
        migrations.AlterField(
            model_name='poojabooking',
            name='pooja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pooja_service.poojaservice'),
        ),
    ]
