# Generated by Django 6.0.6 on 2026-08-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_form', '0002_remove_poojabooking_gotra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojabooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
