# Generated by Django 5.2.3 on 2026-08-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_form', '0003_poojabooking_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poojabooking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
    ]
