# Generated by Django 5.2.3 on 2026-01-07 14:25

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoojaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('describe', tinymce.models.HTMLField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='pooja/')),
            ],
        ),
    ]
