# Generated by Django 5.2.3 on 2026-01-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojaservice',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
