# Generated by Django 6.0.6 on 2026-07-07 10:17

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_service', '0002_poojaservice_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poojaservice',
            options={'verbose_name_plural': 'Pooja Services'},
        ),
        migrations.AddField(
            model_name='poojaservice',
            name='badge',
            field=models.CharField(blank=True, help_text='e.g., Best Seller, Trending', max_length=30, null=True, verbose_name='Special Tag/Badge'),
        ),
        migrations.AddField(
            model_name='poojaservice',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Offer Price (₹) [Optional]'),
        ),
        migrations.AddField(
            model_name='poojaservice',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 2-3 Ghante', max_length=50, null=True, verbose_name='Pooja Ka Samay'),
        ),
        migrations.AddField(
            model_name='poojaservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Website Par Dikhayein?'),
        ),
        migrations.AddField(
            model_name='poojaservice',
            name='is_online_available',
            field=models.BooleanField(default=False, verbose_name='Kya Video Call Par Pooja Ho Sakti Hai?'),
        ),
        migrations.AddField(
            model_name='poojaservice',
            name='samagri_included',
            field=models.BooleanField(default=True, verbose_name='Kya Samagri Price Mein Shamil Hai?'),
        ),
        migrations.AlterField(
            model_name='poojaservice',
            name='describe',
            field=tinymce.models.HTMLField(verbose_name='Pooja Ke Baare Mein Details'),
        ),
        migrations.AlterField(
            model_name='poojaservice',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pooja/', verbose_name='Pooja Ki Photo'),
        ),
        migrations.AlterField(
            model_name='poojaservice',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Actual Price (₹)'),
        ),
        migrations.AlterField(
            model_name='poojaservice',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Pooja Ka Naam'),
        ),
    ]
