# Generated by Django 6.0.6 on 2026-07-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeritagePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Mahakal Mandir', max_length=255)),
                ('description', models.TextField(help_text='Example: Ujjain ka prasiddh Jyotirling Mahakal Mandir.')),
                ('image', models.ImageField(help_text='Card header image', upload_to='heritage_images/')),
                ('slug', models.SlugField(help_text="URL friendly name (e.g., 'mahakal-mandir')", unique=True)),
            ],
            options={
                'verbose_name': 'Heritage Place',
                'verbose_name_plural': 'Heritage Places',
            },
        ),
    ]
