# Generated by Django 6.0.6 on 2026-07-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageplace',
            name='google_map_url',
            field=models.URLField(blank=True, help_text='Google Maps Embed URL', null=True),
        ),
        migrations.AddField(
            model_name='heritageplace',
            name='live_darshan_url',
            field=models.URLField(blank=True, help_text='YouTube Live Embed URL', null=True),
        ),
        migrations.AlterField(
            model_name='heritageplace',
            name='slug',
            field=models.SlugField(help_text='URL friendly name (e.g., mahakal-mandir)', unique=True),
        ),
    ]
